language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
before_install:
  - gem update --system
before_script:
  - bundle exec appraisal install --jobs=3
script:
  - bundle exec rubocop
  - bundle exec appraisal avro-official rspec
  - bundle exec appraisal avro-salsify-fork rspec
